### ISSUE TITLE
Building the Glow model - putting it all together

### ISSUE THREAD

**Issue by Dayan-Zhanchi** [Lunkers/DD2412-Project#10]
Glue together the layers.

- [x] Add squeeze2D equivalent before the step flow layer
- [x] Add split2D equivalent after the step flow layer
- [x] Glue together the layers and debug -> this will probably take some time to get working, dimensionality and other stuff needs to be correct

- [x] Add logic for reverse
- [x] Add logic for logdet and building on previous logdet values
- [x] Fix split with gaussian
- [x] Make sure dimens are correct through the operations
- [x] Check that it trains correctly and optimizes the right parameters (make sure nn.ModuleList works correctly)
- [x] Make sure actnorm, inconv and affine coupling are complete and correct

**Comment by Lunkers** [comment]
I can take a look at the split2D layer

**Comment by Lunkers** [comment]
Also, they refer to the RealNVP paper for details on the split and squeeze layers that wrap the flow steps.
